Toyeeb dev consolidation
nmrs-nigeria/openmrs-module-nmrsmetadata pull request #184
Opened 2021-04-29 16:49 UTC by tobstech

2021-05-04 08:06 UTC, talk2morris requested changes
Hi Toyeeb, your branch has conflict.please resolve conflicts

2021-05-05 12:34 UTC, talk2morris requested changes

2021-05-05 12:34 UTC, talk2morris commented on omod/src/main/webapp/resources/reports/dataset-DataEntrantStatistics.xml
> +<org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition id="1" uuid="4abc7a9b-07b9-4ca5-a406-08708bf63c3b" retired="false">
can u take this file out for now?

2021-05-05 12:44 UTC, tobstech commented on omod/src/main/webapp/resources/reports/dataset-DataEntrantStatistics.xml
> +<org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition id="1" uuid="4abc7a9b-07b9-4ca5-a406-08708bf63c3b" retired="false">
Okay Sir

2021-05-05 12:56 UTC, tobstech commented on omod/src/main/webapp/resources/reports/dataset-DataEntrantStatistics.xml
> +<org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition id="1" uuid="4abc7a9b-07b9-4ca5-a406-08708bf63c3b" retired="false">
Done removed

2021-05-05 13:46 UTC, talk2morris approved these changes

2021-05-05 13:47 UTC, merged