Added data entry statistics report
nmrs-nigeria/openmrs-module-nmrsmetadata pull request #189
Opened 2021-05-07 10:12 UTC by brightoibe

Data Entry Statistics report to audit total number of forms entered by each user account

2021-05-07 11:28 UTC, talk2morris requested changes
I thought this report was already added by Toyeeb?

2021-05-07 12:00 UTC, brightoibe commented
> 
> 
> I thought this report was already added by Toyeeb?

No it has not.

2021-05-10 02:40 UTC, brightoibe commented
> 
> 
> > > I thought this report was already added by Toyeeb?
> > 
> > 
> > No it has not.
> 
> actually it's there.. @brightoibe and @tobstech kindly work together to arrive at a final and optimal solution.

Modifications has been made on the data entry statistics. @tobstech please review and confirm that it works for you

2021-05-10 20:17 UTC, talk2morris approved these changes

2021-05-10 20:17 UTC, merged